#ifndef EEZ_LVGL_UI_VARS_H
#define EEZ_LVGL_UI_VARS_H

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

// enum declarations

// Flow global variables

enum FlowGlobalVariables {
    FLOW_GLOBAL_VARIABLE_ACTIVE_TAB_INDEX = 0,
    FLOW_GLOBAL_VARIABLE_IS_DASH = 1,
    FLOW_GLOBAL_VARIABLE_IS_INV = 2,
    FLOW_GLOBAL_VARIABLE_IS_ACT = 3,
    FLOW_GLOBAL_VARIABLE_DASH_CTG = 4,
    FLOW_GLOBAL_VARIABLE_DASH_TS = 5,
    FLOW_GLOBAL_VARIABLE_DASH_LS = 6,
    FLOW_GLOBAL_VARIABLE_TEM = 7,
    FLOW_GLOBAL_VARIABLE_HUM = 8,
    FLOW_GLOBAL_VARIABLE_SELECTED_CABINET = 9,
    FLOW_GLOBAL_VARIABLE_CABINETS = 10,
    FLOW_GLOBAL_VARIABLE_ELE_CQTY = 11,
    FLOW_GLOBAL_VARIABLE_CN_CSTA = 12,
    FLOW_GLOBAL_VARIABLE_OUTBOUND_QTY = 13,
    FLOW_GLOBAL_VARIABLE_CABINET_COUNT = 14,
    FLOW_GLOBAL_VARIABLE_SHOWERROR = 15,
    FLOW_GLOBAL_VARIABLE_HISTORY_RECORDS = 16,
    FLOW_GLOBAL_VARIABLE_CHOOSE = 17,
    FLOW_GLOBAL_VARIABLE_HISTORY_COUNT = 18,
    FLOW_GLOBAL_VARIABLE_TEMP_NAME = 19,
    FLOW_GLOBAL_VARIABLE_TEMP_QTY = 20,
    FLOW_GLOBAL_VARIABLE_TEMP_PC = 21,
    FLOW_GLOBAL_VARIABLE_TEMP_PA = 22,
    FLOW_GLOBAL_VARIABLE_TEMP_SPEC = 23,
    FLOW_GLOBAL_VARIABLE_SHOW_SELECT_DIALOG = 24,
    FLOW_GLOBAL_VARIABLE_CID = 25,
    FLOW_GLOBAL_VARIABLE_CIDUI = 26,
    FLOW_GLOBAL_VARIABLE_USER = 27,
    FLOW_GLOBAL_VARIABLE_LSW = 28,
    FLOW_GLOBAL_VARIABLE_FLAG_START = 29,
    FLOW_GLOBAL_VARIABLE_FLAG_SAVE = 30,
    FLOW_GLOBAL_VARIABLE_CAM_TEXT = 31
};

// Native global variables

#ifdef __cplusplus
}
#endif

#endif /*EEZ_LVGL_UI_VARS_H*/