################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

C++M_SRCS := 
CPP_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
ELF_SRCS := 
C_UPPER_SRCS := 
CXX_SRCS := 
CCM_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
S_SRCS := 
CC_SRCS := 
C_SRCS := 
CXXM_SRCS := 
CYCLO_FILES := 
OBJDUMP_LIST := 
CCM_DEPS := 
C_UPPER_DEPS := 
S_DEPS := 
CXXM_DEPS := 
C_DEPS := 
OBJCOPY_BIN := 
CC_DEPS := 
SIZE_OUTPUT := 
C++_DEPS := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
CXX_DEPS := 
MAP_FILES := 
S_UPPER_DEPS := 
C++M_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
APP \
APP/ui \
Core/Src \
Core/Startup \
Drivers/BSP/AHT10 \
Drivers/BSP/BUZZER \
Drivers/BSP/EEPROM \
Drivers/BSP/HyperRAM \
Drivers/BSP/IMX335/STM32_IMX335 \
Drivers/BSP/IMX335 \
Drivers/BSP/KEY \
Drivers/BSP/LED \
Drivers/BSP/NORFlash \
Drivers/BSP/Printer \
Drivers/BSP/RGBLCD \
Drivers/BSP/SK9822 \
Drivers/BSP/SYS \
Drivers/BSP/SoftI2C \
Drivers/BSP/TOUCH \
Drivers/BSP/UART \
Drivers/BSP/VL53L1X \
Drivers/STM32N6xx_HAL_Driver \
Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only \
Middlewares/RTOS2/CMSIS/RTOS2/Heap/Heap_4 \
Middlewares/ST/AI/Npu/Devices/STM32N6XX \
Middlewares/ST/AI/Npu/ll_aton \
Middlewares/STM32_MW_ISP/isp/Src \
Middlewares/lvgl-release-v9.4/src/core \
Middlewares/lvgl-release-v9.4/src/display \
Middlewares/lvgl-release-v9.4/src/draw/convert/helium \
Middlewares/lvgl-release-v9.4/src/draw/convert \
Middlewares/lvgl-release-v9.4/src/draw/convert/neon \
Middlewares/lvgl-release-v9.4/src/draw/dma2d \
Middlewares/lvgl-release-v9.4/src/draw/espressif/ppa \
Middlewares/lvgl-release-v9.4/src/draw/eve \
Middlewares/lvgl-release-v9.4/src/draw \
Middlewares/lvgl-release-v9.4/src/draw/nema_gfx \
Middlewares/lvgl-release-v9.4/src/draw/nxp/g2d \
Middlewares/lvgl-release-v9.4/src/draw/nxp/pxp \
Middlewares/lvgl-release-v9.4/src/draw/opengles \
Middlewares/lvgl-release-v9.4/src/draw/renesas/dave2d \
Middlewares/lvgl-release-v9.4/src/draw/sdl \
Middlewares/lvgl-release-v9.4/src/draw/sw/blend/helium \
Middlewares/lvgl-release-v9.4/src/draw/sw/blend \
Middlewares/lvgl-release-v9.4/src/draw/sw/blend/neon \
Middlewares/lvgl-release-v9.4/src/draw/sw \
Middlewares/lvgl-release-v9.4/src/draw/vg_lite \
Middlewares/lvgl-release-v9.4/src/drivers/display/drm \
Middlewares/lvgl-release-v9.4/src/drivers/display/fb \
Middlewares/lvgl-release-v9.4/src/drivers/display/ft81x \
Middlewares/lvgl-release-v9.4/src/drivers/display/ili9341 \
Middlewares/lvgl-release-v9.4/src/drivers/display/lcd \
Middlewares/lvgl-release-v9.4/src/drivers/display/lovyan_gfx \
Middlewares/lvgl-release-v9.4/src/drivers/display/nv3007 \
Middlewares/lvgl-release-v9.4/src/drivers/display/nxp_elcdif \
Middlewares/lvgl-release-v9.4/src/drivers/display/renesas_glcdc \
Middlewares/lvgl-release-v9.4/src/drivers/display/st7735 \
Middlewares/lvgl-release-v9.4/src/drivers/display/st7789 \
Middlewares/lvgl-release-v9.4/src/drivers/display/st7796 \
Middlewares/lvgl-release-v9.4/src/drivers/display/st_ltdc \
Middlewares/lvgl-release-v9.4/src/drivers/display/tft_espi \
Middlewares/lvgl-release-v9.4/src/drivers/draw/eve \
Middlewares/lvgl-release-v9.4/src/drivers/evdev \
Middlewares/lvgl-release-v9.4/src/drivers/libinput \
Middlewares/lvgl-release-v9.4/src/drivers/nuttx \
Middlewares/lvgl-release-v9.4/src/drivers/opengles/assets \
Middlewares/lvgl-release-v9.4/src/drivers/opengles/glad/src \
Middlewares/lvgl-release-v9.4/src/drivers/opengles \
Middlewares/lvgl-release-v9.4/src/drivers/opengles/opengl_shader \
Middlewares/lvgl-release-v9.4/src/drivers/qnx \
Middlewares/lvgl-release-v9.4/src/drivers/sdl \
Middlewares/lvgl-release-v9.4/src/drivers/uefi \
Middlewares/lvgl-release-v9.4/src/drivers/wayland \
Middlewares/lvgl-release-v9.4/src/drivers/windows \
Middlewares/lvgl-release-v9.4/src/drivers/x11 \
Middlewares/lvgl-release-v9.4/src/font \
Middlewares/lvgl-release-v9.4/src/indev \
Middlewares/lvgl-release-v9.4/src/layouts/flex \
Middlewares/lvgl-release-v9.4/src/layouts/grid \
Middlewares/lvgl-release-v9.4/src/layouts \
Middlewares/lvgl-release-v9.4/src/libs/FT800-FT813 \
Middlewares/lvgl-release-v9.4/src/libs/barcode \
Middlewares/lvgl-release-v9.4/src/libs/bin_decoder \
Middlewares/lvgl-release-v9.4/src/libs/bmp \
Middlewares/lvgl-release-v9.4/src/libs/expat \
Middlewares/lvgl-release-v9.4/src/libs/ffmpeg \
Middlewares/lvgl-release-v9.4/src/libs/freetype \
Middlewares/lvgl-release-v9.4/src/libs/frogfs/src \
Middlewares/lvgl-release-v9.4/src/libs/fsdrv \
Middlewares/lvgl-release-v9.4/src/libs/gif/AnimatedGIF/src \
Middlewares/lvgl-release-v9.4/src/libs/gif \
Middlewares/lvgl-release-v9.4/src/libs/gltf/gltf_data \
Middlewares/lvgl-release-v9.4/src/libs/gltf/gltf_view/assets \
Middlewares/lvgl-release-v9.4/src/libs/gltf/gltf_view/ibl \
Middlewares/lvgl-release-v9.4/src/libs/gltf/gltf_view \
Middlewares/lvgl-release-v9.4/src/libs/gltf/math \
Middlewares/lvgl-release-v9.4/src/libs/gstreamer \
Middlewares/lvgl-release-v9.4/src/libs/libjpeg_turbo \
Middlewares/lvgl-release-v9.4/src/libs/libpng \
Middlewares/lvgl-release-v9.4/src/libs/lodepng \
Middlewares/lvgl-release-v9.4/src/libs/lz4 \
Middlewares/lvgl-release-v9.4/src/libs/qrcode \
Middlewares/lvgl-release-v9.4/src/libs/rle \
Middlewares/lvgl-release-v9.4/src/libs/rlottie \
Middlewares/lvgl-release-v9.4/src/libs/svg \
Middlewares/lvgl-release-v9.4/src/libs/thorvg \
Middlewares/lvgl-release-v9.4/src/libs/tiny_ttf \
Middlewares/lvgl-release-v9.4/src/libs/tjpgd \
Middlewares/lvgl-release-v9.4/src/libs/vg_lite_driver/VGLite \
Middlewares/lvgl-release-v9.4/src/libs/vg_lite_driver/VGLiteKernel \
Middlewares/lvgl-release-v9.4/src/libs/vg_lite_driver/lv_vg_lite_hal \
Middlewares/lvgl-release-v9.4/src \
Middlewares/lvgl-release-v9.4/src/misc/cache/class \
Middlewares/lvgl-release-v9.4/src/misc/cache/instance \
Middlewares/lvgl-release-v9.4/src/misc/cache \
Middlewares/lvgl-release-v9.4/src/misc \
Middlewares/lvgl-release-v9.4/src/osal \
Middlewares/lvgl-release-v9.4/src/others/file_explorer \
Middlewares/lvgl-release-v9.4/src/others/font_manager \
Middlewares/lvgl-release-v9.4/src/others/fragment \
Middlewares/lvgl-release-v9.4/src/others/gridnav \
Middlewares/lvgl-release-v9.4/src/others/ime \
Middlewares/lvgl-release-v9.4/src/others/imgfont \
Middlewares/lvgl-release-v9.4/src/others/monkey \
Middlewares/lvgl-release-v9.4/src/others/observer \
Middlewares/lvgl-release-v9.4/src/others/snapshot \
Middlewares/lvgl-release-v9.4/src/others/sysmon \
Middlewares/lvgl-release-v9.4/src/others/test \
Middlewares/lvgl-release-v9.4/src/others/translation \
Middlewares/lvgl-release-v9.4/src/others/vg_lite_tvg \
Middlewares/lvgl-release-v9.4/src/others/xml \
Middlewares/lvgl-release-v9.4/src/others/xml/parsers \
Middlewares/lvgl-release-v9.4/src/stdlib/builtin \
Middlewares/lvgl-release-v9.4/src/stdlib/clib \
Middlewares/lvgl-release-v9.4/src/stdlib \
Middlewares/lvgl-release-v9.4/src/stdlib/micropython \
Middlewares/lvgl-release-v9.4/src/stdlib/rtthread \
Middlewares/lvgl-release-v9.4/src/stdlib/uefi \
Middlewares/lvgl-release-v9.4/src/themes/default \
Middlewares/lvgl-release-v9.4/src/themes \
Middlewares/lvgl-release-v9.4/src/themes/mono \
Middlewares/lvgl-release-v9.4/src/themes/simple \
Middlewares/lvgl-release-v9.4/src/tick \
Middlewares/lvgl-release-v9.4/src/widgets/3dtexture \
Middlewares/lvgl-release-v9.4/src/widgets/animimage \
Middlewares/lvgl-release-v9.4/src/widgets/arc \
Middlewares/lvgl-release-v9.4/src/widgets/arclabel \
Middlewares/lvgl-release-v9.4/src/widgets/bar \
Middlewares/lvgl-release-v9.4/src/widgets/button \
Middlewares/lvgl-release-v9.4/src/widgets/buttonmatrix \
Middlewares/lvgl-release-v9.4/src/widgets/calendar \
Middlewares/lvgl-release-v9.4/src/widgets/canvas \
Middlewares/lvgl-release-v9.4/src/widgets/chart \
Middlewares/lvgl-release-v9.4/src/widgets/checkbox \
Middlewares/lvgl-release-v9.4/src/widgets/dropdown \
Middlewares/lvgl-release-v9.4/src/widgets/image \
Middlewares/lvgl-release-v9.4/src/widgets/imagebutton \
Middlewares/lvgl-release-v9.4/src/widgets/keyboard \
Middlewares/lvgl-release-v9.4/src/widgets/label \
Middlewares/lvgl-release-v9.4/src/widgets/led \
Middlewares/lvgl-release-v9.4/src/widgets/line \
Middlewares/lvgl-release-v9.4/src/widgets/list \
Middlewares/lvgl-release-v9.4/src/widgets/lottie \
Middlewares/lvgl-release-v9.4/src/widgets/menu \
Middlewares/lvgl-release-v9.4/src/widgets/msgbox \
Middlewares/lvgl-release-v9.4/src/widgets/objx_templ \
Middlewares/lvgl-release-v9.4/src/widgets/property \
Middlewares/lvgl-release-v9.4/src/widgets/roller \
Middlewares/lvgl-release-v9.4/src/widgets/scale \
Middlewares/lvgl-release-v9.4/src/widgets/slider \
Middlewares/lvgl-release-v9.4/src/widgets/span \
Middlewares/lvgl-release-v9.4/src/widgets/spinbox \
Middlewares/lvgl-release-v9.4/src/widgets/spinner \
Middlewares/lvgl-release-v9.4/src/widgets/switch \
Middlewares/lvgl-release-v9.4/src/widgets/table \
Middlewares/lvgl-release-v9.4/src/widgets/tabview \
Middlewares/lvgl-release-v9.4/src/widgets/textarea \
Middlewares/lvgl-release-v9.4/src/widgets/tileview \
Middlewares/lvgl-release-v9.4/src/widgets/win \
X-CUBE-AI/App \

